name: Merge dependency updates

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "ORCA CI"

permissions:
  contents: write
  pull-requests: write

jobs:
  call-workflow:
    uses: acquia/cli/.github/workflows/automerge.yml@main
