name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  call-workflow:
    uses: acquia/cli/.github/workflows/release-drafter.yml@main
